# Generated by Django 4.2.30 on 2026-09-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripction',
            new_name='description',
        ),
    ]
