# Generated by Django 4.2.30 on 2026-09-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True)),
                ('height', models.PositiveIntegerField(help_text='Altura en decimetros (segun la PokeAPI)')),
                ('weight', models.PositiveIntegerField(help_text='Peso en hectogramos (segun la PokeAPI)')),
                ('base_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('types', models.ManyToManyField(blank=True, related_name='pokemons', to='pokemons.pokemontype')),
            ],
        ),
    ]
