# Generated by Django 4.2.30 on 2026-09-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.JSONField(blank=True, default=list, help_text='Lista de {name, is_hidden} segun la PokeAPI'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_attack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_defense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
